### ISSUE TITLE
Appfile is reloaded many times

### ISSUE THREAD

**Issue by lacostej** [fastlane/credentials_manager#30]
Appfile is reloaded at every request when querying using `try_fetch_value`. Is that by design ?

See https://github.com/fastlane/credentials_manager/blob/0.14.0/lib/credentials_manager/appfile_config.rb#L5-L13

**Comment by KrauseFx** [comment]
I agree, this could be improved

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1924. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
