### ISSUE TITLE
the messages do not show when called recursively

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/credentials_manager#31]
we are using tsmessage library to display no network message with a tap to retry button. within the handler of the retry button we reload the viewController using a call to viewDidAppeare() . The problem is that after a retry when the request fails the message do not display on the screen again, the log shows that the request is made and it has failed also the statement to show the message is called. The message display works when we deselect the current tab and reselect the same tab again inside the handler of the retry button. please help us solve this problem if it is in any way related to this library

thanks
santosh

----

Original issue by @izuzak

**Comment by KrauseFx** [comment]
Hi, this is a comment added after the import

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1923. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
